name: "Spoolman Server"
version: 0.20.0
description: "Run the latest stable version of Spoolman."
url: "https://github.com/donkie/spoolman"
slug: "spoolman"
init: false
arch:
  - aarch64
  - amd64
  - armv7
startup: application
udev: true
webui: "[PROTO:option_name]://[HOST]:[PORT:8000]"
environment:
  SPOOLMAN_DIR_DATA: "/config/spoolman"
map:
  # - config:rw
  - addon_config:rw
boot: auto
ports:
  8000/tcp: 8000
image: ghcr.io/donkie/spoolman
