name: Host Iptables
description: Apply iptables rules
version: 1.0.5
slug: iptables
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
host_network: true
map:
  - type: addon_config
    read_only: true
privileged:
  - NET_ADMIN
options:
  restore: false
  Stay_up: true
schema:
  restore: bool
  Stay_up: bool
