name: "Part-DB Server"
version: v1.17.4
# version: master
description: "Part-DB is an Open-Source inventory management system for your electronic components. It is installed on a web server and so can be accessed with any browser without the need to install additional software."
url: "https://docs.part-db.de/"
slug: "partdb"
arch:
  - aarch64
  - amd64
  - armv7
startup: application
init: true
legacy: true
# watchdog: http://[HOST]:[PORT:2019]/metrics
webui: "[PROTO:option_name]://[HOST]:[PORT:80]"
map:
  - type: ssl
    read_only: true
  - type: addon_config
    read_only: false
    path: /var/www/html/var/db
  - type: data
    path: /var/www/html/public/media
    read_only: false
  - type: share
    path: /var/www/html/uploads
    read_only: false
  - type: backup
    read_only: false
boot: auto
ports:
  80/tcp: 8070
  443/tcp: 8470
  443/udp: 8470
ports-description:
  80/tcp: "Web interface"
  443/tcp: "Web interface"
  443/udp: "Web interface"
  2019/tcp: "health check"
environment:
  DATABASE_URL: "sqlite:///%kernel.project_dir%/var/db/app.db"
  APP_ENV: docker
  ALLOW_ATTACHMENT_DOWNLOADS: "1"
options:
  USE_GRAVATAR: 1
  ATTACHMENT_DOWNLOAD_BY_DEFAULT: 1
  PROVIDER_LCSC_ENABLED: 1
  PROVIDER_REICHELT_ENABLED: 1
  PROVIDER_POLLIN_ENABLED: 1
schema:
  TRUSTED_PROXIES: str?
  TRUSTED_HOSTS: str?
  DEFAULT_URI: url?
  USE_GRAVATAR: int(0,1)
  ATTACHMENT_DOWNLOAD_BY_DEFAULT: int(0,1)
  PROVIDER_LCSC_ENABLED: int(0,1)
  PROVIDER_REICHELT_ENABLED: int(0,1)
  PROVIDER_POLLIN_ENABLED: int(0,1)

  PROVIDER_DIGIKEY_CLIENT_ID: str?
  PROVIDER_DIGIKEY_CLIENT_SECRET: str?
  PROVIDER_DIGIKEY_COUNTRY: str?

  PROVIDER_TME_KEY: str?
  PROVIDER_TME_SECRET: str?
  PROVIDER_TME_COUNTRY: str?

  PROVIDER_ELEMENT14_KEY: str?
  PROVIDER_ELEMENT14_STORE_ID: str?

  PROVIDER_MOUSER_KEY: str?
  PROVIDER_MOUSER_SEARCH_LIMIT: int(1,50)?

  PROVIDER_OEMSECRETS_KEY: str?
  PROVIDER_OEMSECRETS_COUNTRY_CODE: str?
  PROVIDER_OEMSECRETS_ZERO_PRICE: int(0,1)?
  PROVIDER_OEMSECRETS_SET_PARAM: int(0,1)?

  PROVIDER_OCTOPART_CLIENT_ID: str?
  PROVIDER_OCTOPART_SECRET: str?
  PROVIDER_OCTOPART_COUNTRY: str?
  PROVIDER_OCTOPART_SEARCH_LIMIT: int(1,100)?
  PROVIDER_OCTOPART_ONLY_AUTHORIZED_SELLERS: bool?

  FIXER_API_KEY: str?
  BANNER: str?
image: jbtronics/part-db1
backup: hot
backup_pre: |
  #!/bin/bash
  su -s /bin/sh  www-data -c 'php /var/www/html/bin/console partdb:attachments:clean-unused 2>&1 > /dev/null'
  su -s /bin/sh  www-data -c 'php /var/www/html/bin/console cache:clear'
  su -s /bin/sh  www-data -c 'php /var/www/html/bin/console partdb:backup --full /backup/partdb/Part-DB_backup.zip'
backup_post: |
  #!/bin/bash
  # rm /backup/partdb/Part-DB_backup.zip




