name: "Part-DB Server"
version: v1.16.1
description: "Part-DB is an Open-Source inventory management system for your electronic components. It is installed on a web server and so can be accessed with any browser without the need to install additional software."
url: "https://docs.part-db.de/"
slug: "partdb"
arch:
  - aarch64
  - amd64
  - armv7

startup: application
# init: false
legacy: true
# watchdog: http://[HOST]:[PORT:2019]/metrics
webui: "[PROTO:option_name]://[HOST]:[PORT:80]"
map:
  - type: ssl
    read_only: true
  - type: addon_config
    read_only: false
    path: /var/www/html/config
  - type: data
    read_only: false
    path: /var/www/html/var/db
  - type: share
    read_only: false
    path: /var/www/html/uploads
  - type: backup
    read_only: false
boot: auto
ports:
  80/tcp: 8070
  443/tcp: 8470
  443/udp: 8470
ports-description:
  80/tcp: "Web interface"
  443/tcp: "Web interface"
  443/udp: "Web interface"
  2019/tcp: "health check"
environment:
  DATABASE_URL: "sqlite:///%kernel.project_dir%/var/db/app.db"
  APP_ENV: docker
  ALLOW_ATTACHMENT_DOWNLOADS: "1"
  USE_GRAVATAR: "1"
  PROVIDER_LCSC_ENABLED: "1"
  PROVIDER_REICHELT_ENABLED: "1"
  PROVIDER_POLLIN_ENABLED: "1"
options:
  USE_GRAVATAR: true
  # PROVIDER_DIGIKEY_CLIENT_ID:
  # PROVIDER_DIGIKEY_CLIENT_SECRET:
  # PROVIDER_DIGIKEY_COUNTRY:
  # PROVIDER_MOUSER_KEY:
  # PROVIDER_OEMSECRETS_KEY:
schema:
  USE_GRAVATAR: bool
  PROVIDER_DIGIKEY_CLIENT_ID: str?
  PROVIDER_DIGIKEY_CLIENT_SECRET: str?
  PROVIDER_DIGIKEY_COUNTRY: str?
  PROVIDER_MOUSER_KEY: str?
  PROVIDER_OEMSECRETS_KEY: str?
image: jbtronics/part-db1
backup: hot
